version: '3.4'

services:
  pdfgenerator:
    image: ${DOCKER_REGISTRY-}pdfgenerator
    environment:
        Pdf__GeneratorUrl: "http://host.docker.internal:3000"
    ports:
      - "8085:80"
    build:
      context: .
      dockerfile: PdfGenerator/Dockerfile

  pdf-generator-gotenberg:
    image: thecodingmachine/gotenberg:6
    ports:
      - "3000:3000"

  wish-me-swaggerui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "3200:8080"
    environment:
      URLS: '[ { url: " http://localhost:8085/docs/v1/swagger.json", name: "Pdf Generator" } ]'
